### ISSUE TITLE
How might one rework getRep to return mulitple instances.

### ISSUE THREAD

**Issue by twobob** [UoA-eResearch/openface_mass_compare#5]
```
def getRep(bgrImg, align=align, net=net):
    rgbImg = cv2.cvtColor(bgrImg, cv2.COLOR_BGR2RGB)
    bb = align.getLargestFaceBoundingBox(rgbImg)
    if bb is None:
        raise Exception("Unable to find a face")
    alignedFace = align.align(96, rgbImg, bb, landmarkIndices=openface.AlignDlib.OUTER_EYES_AND_NOSE)
    if alignedFace is None:
        raise Exception("Unable to align image")
    rep = net.forward(alignedFace)
    return rep 
```
I tried
```
def getReps(bgrImg, align=align, net=net):
    holder=[]
    rgbImg = cv2.cvtColor(bgrImg, cv2.COLOR_BGR2RGB)
    bb = align.getAllFaceBoundingBoxes(rgbImg)
    if bb is None:
        raise Exception("Unable to find a face")
    for face in bb:
        alignedFace = align.align(96, rgbImg, face, landmarkIndices=openface.AlignDlib.OUTER_EYES_AND_NOSE)
        if alignedFace is None:
            print("Unable to align image")
            continue
        if not alignedFace is None:
            rep = net.forward(alignedFace)
            print("did rep", rep)
            holder.append(rep)
    return holder 
```
But I am a little confused how to handle to output.
I read http://openface-api.readthedocs.io/en/latest/openface.html
and thought I would jut receive a list of rectangles from align
which I could walk but now I am a little confused as to a) how to check which actual images matched which face and which names that pertained to.

Anyway, it's just a question really.  Many thanks

**Comment by neon-ninja** [comment]
Looks good to me. getAllFaceBoundingBox returns the bounding boxes for each face (left,top,width,height - http://dlib.net/python/#dlib.rectangle), so I'd recommend recording which bounding box corresponds to which net.forward matrix (maybe with a dict). To compare against other matrices you can perform the same math as in https://github.com/UoA-eResearch/openface_mass_compare/blob/master/web_server.py#L90 - 
```
d = rep - r  
dot = np.dot(d,d)
```
where lowest dot product = best match. If you respond with bounding box + closest match you can overlay rectangles on the source image with a text overlay for identifier

**Comment by twobob** [comment]
I figured it in the end and reworked the workflow to be primarily server centric.
got it to return multiple data per image now
![image](https://cloud.githubusercontent.com/assets/915232/26130315/fb9b9b8c-3a8b-11e7-8534-3102d8d6af2f.png)
my workflow is probably klunky but working purely on MS has its unique requirements.

we included 300 ish training files over 18 classes
we provided exactly "one" of each type of a random person for 300 ish in the unknown class.

in terms of confidence, we wished to track total hits for a class and just assumed a base confidence, with a simple python pass to exclude any results from the unknown class, post classification. A kind of "bit-bucket exception management approach", after initial recognition and that discriminatory pass all confidence was ignored.

Quick question: In the final "infer" stage when retrieving a result, is there a "fastest" best practice to retrieve a result back from the SVM pkl. I think I noted two approaches in the various demos to gain classification, a grid search was one certainly. I'll dig back around and try to ask a more coherent question, however, multiple results are now being parsed thank you.  

A worked demo to do multiple classification, with images in a folder, would be very much appreciated.
Should you ever fancy expanding your demos.

**Comment by neon-ninja** [comment]
The reason I store matrices in a pickle, is that when they're precomputed, checking against them is much faster. You need to compare the computed matrix against every precomputed matrix, potentially to speed this up you could check in parallel in batches. I've found checking single threaded against 4000+ matrices can be done in under a second.

**Comment by neon-ninja** [comment]
Hey  - Microsoft made some changes to their API to restrict free accounts to 1 month trials. So I've been revisiting https://github.com/UoA-eResearch/hololens_facial_recognition to try and get it working again - I'm using a wrapper script around faceplusplus and kairos with https://github.com/UoA-eResearch/face_api

So while I'm revisiting this, I wanted to try and optimise speed. For that, I want to be able to send out all requests to external apis at once. So I needed openface_mass_compare to support multiple faces. I've pushed a commit similar to what you've done with getAllFaceBoundingBoxes - it's https://github.com/UoA-eResearch/openface_mass_compare/commit/19337dcc8df31c3e3b8e1ff42eb2eda1d90e0a09
